export const tanks = [
  {
    id: 1,
    name: "ACR_US_TECH_2019",
    programme: "ACR",
    country: "US",
    afolu: "TECH",
    vintage: "2019",
    maxQty: 250000,
    currentQty: 0,
    remainingCapacity: null,
    setRemainingCapacity: function () {
      this.remainingCapacity = this.maxQty - this.currentQty;
    },
    contents: [],
  },
  {
    id: 2,
    name: "ACR_US_TECH_2021",
    programme: "ACR",
    country: "US",
    afolu: "TECH",
    vintage: "2021",
    maxQty: 983472,
    currentQty: 0,
    remainingCapacity: null,
    setRemainingCapacity: function () {
      this.remainingCapacity = this.maxQty - this.currentQty;
    },
    contents: [],
  },
  {
    id: 3,
    name: "CAR_US_TECH_2010",
    programme: "CAR",
    country: "US",
    afolu: "TECH",
    vintage: "2010",
    maxQty: 9000,
    currentQty: 0,
    remainingCapacity: null,
    setRemainingCapacity: function () {
      this.remainingCapacity = this.maxQty - this.currentQty;
    },
    contents: [],
  },
  {
    id: 4,
    name: "VCS_BD_METHR_2019",
    programme: "VCS",
    country: "BD",
    afolu: "METHR",
    vintage: "2019",
    maxQty: 83509,
    currentQty: 0,
    remainingCapacity: null,
    setRemainingCapacity: function () {
      this.remainingCapacity = this.maxQty - this.currentQty;
    },
    contents: [],
  },
];

export const inventory = [
  {
    symbol: "12488AFD37",
    vintage: "2019",
    programme: "ACR",
    qty: 250000,
    country: "US",
    possibleTanks: [1, 2],
    isInTank: false,
  },
  {
    symbol: "12489AFD37",
    vintage: "2021",
    programme: "ACR",
    qty: 100000,
    country: "US",
    possibleTanks: [2, 3],
    isInTank: false,
  },
  {
    symbol: "12490AFD37",
    vintage: "2021",
    programme: "ACR",
    qty: 200000,
    country: "US",
    possibleTanks: [2, 1],
    isInTank: false,
  },
  {
    symbol: "12491AFD37",
    vintage: "2021",
    programme: "ACR",
    qty: 100000,
    country: "US",
    possibleTanks: [1, 3],
    isInTank: false,
  },
  {
    symbol: "12492AFD37",
    vintage: "2021",
    programme: "ACR",
    qty: 100000,
    country: "US",
    possibleTanks: [2, 4],
    isInTank: false,
  },
  {
    symbol: "12493AFD37",
    vintage: "2021",
    programme: "ACR",
    qty: 183472,
    country: "US",
    possibleTanks: [3, 4],
    isInTank: false,
  },
  {
    symbol: "12494AFD37",
    vintage: "2021",
    programme: "ACR",
    qty: 100000,
    country: "US",
    possibleTanks: [],
    isInTank: false,
  },
  {
    symbol: "12495AFD37",
    vintage: "2021",
    programme: "ACR",
    qty: 200000,
    country: "US",
    possibleTanks: [],
    isInTank: false,
  },
  {
    symbol: "12496AFD37",
    vintage: "2010",
    programme: "CAR",
    qty: 9000,
    country: "US",
    possibleTanks: [],
    isInTank: false,
  },
  {
    symbol: "12497AFD37",
    vintage: "2019",
    programme: "VCS",
    qty: 83509,
    country: "BD",
    possibleTanks: [],
    isInTank: false,
  },
];
